#!/bin/sh
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"break1\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"123\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"break2\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"1234\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"break3\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"1235\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"break4\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"1236\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"break5\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"1237\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"break6\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"1238\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"command\":\"break\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break 1\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"1239\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break 2\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12310\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break 3\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12311\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break 4\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12312\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"command\":\"break\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break2 1\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12313\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break2 2\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12314\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break2 3\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12315\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break2 4\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12316\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"command\":\"break\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break3 1\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12317\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break3 2\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12318\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break3 3\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12319\"}"
mosquitto_pub -d -t IQSend -u IQRight -P 123456 -m "{\"name\":\"After break3 4\", \"level1\":\"lalala\",\"level2\":\"lelele\",\"externalNumber\":\"12320\"}"